// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0IMFFtomlGH_OkRy4Gc6TuQwus2a01TM',
    appId: '1:1032861146105:web:7d4c8e02ba070434ce7b28',
    messagingSenderId: '1032861146105',
    projectId: 'laptrinh-tbdd',
    authDomain: 'laptrinh-tbdd.firebaseapp.com',
    storageBucket: 'laptrinh-tbdd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMTAFiWhoSO4PIwzqFPS9Z85OyNQlftfM',
    appId: '1:1032861146105:android:d6c29ba745908cf0ce7b28',
    messagingSenderId: '1032861146105',
    projectId: 'laptrinh-tbdd',
    storageBucket: 'laptrinh-tbdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2IPtGigTiPFXiA5-3sKuC26r3s_ZfSe4',
    appId: '1:1032861146105:ios:4c327bea8750d9bece7b28',
    messagingSenderId: '1032861146105',
    projectId: 'laptrinh-tbdd',
    storageBucket: 'laptrinh-tbdd.firebasestorage.app',
    iosBundleId: 'com.example.baitapLaptrinhtbdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2IPtGigTiPFXiA5-3sKuC26r3s_ZfSe4',
    appId: '1:1032861146105:ios:4c327bea8750d9bece7b28',
    messagingSenderId: '1032861146105',
    projectId: 'laptrinh-tbdd',
    storageBucket: 'laptrinh-tbdd.firebasestorage.app',
    iosBundleId: 'com.example.baitapLaptrinhtbdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0IMFFtomlGH_OkRy4Gc6TuQwus2a01TM',
    appId: '1:1032861146105:web:8eebfa6e325e1d80ce7b28',
    messagingSenderId: '1032861146105',
    projectId: 'laptrinh-tbdd',
    authDomain: 'laptrinh-tbdd.firebaseapp.com',
    storageBucket: 'laptrinh-tbdd.firebasestorage.app',
  );
}
